
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-client
  template:
    metadata:
      labels:
        app: greeter-client
    spec:
      containers:
      - args:
        - --address=greeter:50051
        - --insecure=true
        image: marcoamador/grpc-greeter-go-client:5
        imagePullPolicy: Always
        name: greeter-client
        ports:
        - containerPort: 8080
---
